# Generated by Django 4.1.2 on 2022-10-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('destination', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('intro', models.TextField(blank=True, max_length=500)),
                ('activities', models.TextField(blank=True, max_length=500)),
                ('activity_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('food', models.TextField(blank=True, max_length=500)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('additional_info', models.TextField(blank=True, max_length=500)),
                ('additional_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('top_destination', models.BooleanField(default=False)),
            ],
        ),
    ]
