# Generated by Django 4.1.2 on 2022-11-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveldestinations',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Travel Destinations'},
        ),
        migrations.AddField(
            model_name='traveldestinations',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
