# Generated by Django 4.1.2 on 2022-11-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0002_alter_traveldestinations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldestinations',
            name='destination_subheading',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
