# Generated by Django 4.1.2 on 2022-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0004_rename_traveldestinations_destinations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Travel Destinations'},
        ),
        migrations.AddField(
            model_name='destinations',
            name='slug',
            field=models.SlugField(default=12, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
