# Generated by Django 4.1.2 on 2023-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0005_alter_destinations_options_destinations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='activities',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='additional_info',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='food',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='intro',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
